### ISSUE TITLE
cp: missing destination file operand after '/etc/default/grub{,.bak}'

### ISSUE THREAD

**Issue by tristan-k** [Upinel/PVE-Intel-vGPU-Lazy#1]
```
i915-sriov-dkms/6.5.13-3, 6.5.13-3-pve, x86_64: installed

********************************************
***  Enable IO-MMU on proxmox host       ***
********************************************
cp: missing destination file operand after '/etc/default/grub{,.bak}'
Try 'cp --help' for more information.

    Update grub ....
Generating grub configuration file ...
```

There seems to be something work with the `cp` command in your shell script.

**Comment by Upinel** [comment]
It is just a backup for original grub bootloader, as Prerequisites stated:
Before proceeding, ensure the following:
• VT-d (IOMMU) and SR-IOV are enabled in BIOS.
• Proxmox Virtual Environment (VE) version 8.1.4 or newer is installed with **GRUB bootloader**.
• EFI is enabled, and Secure Boot is disabled.

If you are not using GRUB, or your proxmox is using custom GRUB bootloader (e.g. not the Proxmox installation iso auto install), you might need to follow the step by step guide or use as your own risk.

Hope that explain well, coz the lazy script is only capable and tested on standard installation otherwise it will have too many alternative need to handle. :D
